<?php
$n=$_GET["n"];
$e=$_GET["e"];
$m=$_GET["m"];
$c=$_GET["c"];
$b=$_GET["b"];
$s=$_GET["s"];
$list=file("data/list.data");
$x=0;
while($x<count($list))
{
	$list[$x]=substr($list[$x],0,strlen($list[$x])-1);
	$x++;
}
$x=count($list)-1;
$flag=0;
while($x>=0)
{
	if(strcmp($e,$list[$x-5])==0 || strcmp($m,$list[$x-4])==0)
	{
		$flag=1;
		break;
	}
	$x=$x-7;
}
if($flag)
{
	print "Already Registered!";
}
else
{
	$f=fopen("data/list.data","a");
	fputs($f,$n);
	fputs($f,"\n");
	fputs($f,$e);
	fputs($f,"\n");
	fputs($f,$m);
	fputs($f,"\n");
	fputs($f,$c);
	fputs($f,"\n");
	fputs($f,$b);
	fputs($f,"\n");
	fputs($f,$s);
	fputs($f,"\n");
	fputs($f,$list[count($list)-1]+1);
	fputs($f,"\n");
	fclose($f);	

	print "Registration Successfull!";
}
?>